name: receive_whatsapp_chat
description: A flutter plugin that enables flutter apps to receive exported chats from WhatsApp.
version: 0.1.4
homepage: https://github.com/dtkdt100/receive_whatsapp_chat

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  path_provider: ^2.1.1
  collection: ^1.17.2
  flutter_archive: ^5.0.0
  receive_sharing_intent: ^1.4.5
#    git:
#      url: https://github.com/AyushmanG26/receive_sharing_intent.git
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.whatsapp.receive_whatsapp_chat
        pluginClass: ReceiveWhatsappChatPlugin
      ios:
        pluginClass: ReceiveWhatsappChatPlugin

